[project]
name = "amoura-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "black>=25.11.0",
    "fastapi>=0.121.1",
    "uvicorn>=0.38.0",
]
